### ISSUE TITLE
[BUG] Database error when clicking on threads

### ISSUE THREAD

**Issue by jpeterson1346** [VATUSA/forums#3]
### Contact Details

VATUSA9

### What happened?

Database error when clicking on threads

### How can it be reproduced?

On mobile, it occurred (not every single time) when I would click on a topic or category. I could press the back button and return to where I was but if I clicked again, it would do the same thing.

### What browsers are you seeing the problem on?

Chrome

### Screenshots

![image](https://user-images.githubusercontent.com/9057104/127178194-b7a5b511-6ec8-4210-a6ab-d2dfcd3fc198.png)

**Comment by dhawton** [comment]
Investigating. If possible, do you know around what time this was encountered?

**Comment by bnahin** [comment]
Reopening; monitoring.

**Comment by dhawton** [comment]
Issue not resolved. Issue of Database Error: Incorrect string value: '''' for function inet_aton still persists. Continuing investigation.

**Comment by dhawton** [comment]
Issue appears resolved. No logged entries since PR #6. Marking this closed, but will continue monitoring.
