### ISSUE TITLE
[BUG] Database error accessing EVENTS

### ISSUE THREAD

**Issue by MacMinnS** [VATUSA/forums#5]
### Contact Details

skylar.hutter@zabartcc.org

### What happened?

Any link to the calendar or events forum or events posts are giving a "Database Error" in the header 

https://forums.vatusa.net/index.php?board=8.0

### How can it be reproduced?

https://forums.vatusa.net/index.php?board=8.0

### What browsers are you seeing the problem on?

Firefox

**Comment by bnahin** [comment]
Duplicate of #3.
